site_name: alexy-dot's blog
site_url: https://alexy-dot.github.io/
site_description: alexy-dot 的个人博客
site_author: alexy-dot
repo_name: alexy-dot/alexy-dot.github.io
repo_url: https://github.com/alexy-dot/alexy-dot.github.io
edit_uri: edit/master/docs/
copyright: Copyright &copy; 2024 - Present <a href="https://github.com/alexy-dot/" target="_blank" rel="noopener">alexy-dot</a>

theme:
  name: material
  language: zh
  custom_dir: overrides
  logo: assets/images/site-icon.png
  favicon: assets/images/site-icon.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  features:
    - content.code.copy
    - content.code.select
    - content.action.view
    - header.autohide
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.path
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
  font: false
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: follow system
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: dark mode

markdown_extensions:
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      auto_title: true
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    absolute_links: ignore
    unrecognized_links: ignore

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alexy-dot
      name: GitHub
    - icon: fontawesome/brands/weixin
      link: about/#contact
      name: WeChat

extra_css:
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - css/custom.css
  - css/flink.css

plugins:
  - search
  - glightbox:
      width: 80%
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      enable_creation_date: true
      exclude:
        - index.md
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      css_files:
        - css/custom.css
        - css/flink.css

nav:
  - Home:
      - index.md
      - about.md
  - Blog:
      - Blogs/index.md
      - Blogs/archives.md
  - Links: Links.md
